language: generic
sudo: required
services:
  - docker

# LLVM takes awhile to check out and otherwise we'll manage the submodules in
# our configure script, so disable auto submodule management.
git:
  submodules: false

before_install:
  - docker build -t rust -f src/etc/Dockerfile src/etc

install:
  - docker run -v `pwd`:/build rust
    sh -c "
      ./configure --llvm-root=/usr/lib/llvm-3.7
    "
  - docker run -v `pwd`:/build rust
    sh -c "
      make tidy
    "
before_script:
  - docker run -v `pwd`:/build rust
    sh -c "
      make all -j4
    "
script:
  - docker run -v `pwd`:/build rust
    sh -c "
      make check-stage2 -j4
    "

# Real testing happens on http://buildbot.rust-lang.org/
#
# See https://github.com/rust-lang/rust-buildbot
#     CONTRIBUTING.md#pull-requests

notifications:
  email: false

branches:
  only:
    - master
